const S=document.getElementById('stage'),bar=document.getElementById('bar'),music=document.getElementById('music'),mb=document.getElementById('musicBtn');let step=0,mem=0,audio;
const photos=['https://picsum.photos/seed/chantytravel1/900/1100','https://picsum.photos/seed/chantytravel2/900/1100','https://picsum.photos/seed/chantyfriends3/900/1100','https://picsum.photos/seed/chantyclass4/900/1100','https://picsum.photos/seed/chantyclass5/900/1100','https://picsum.photos/seed/chantytravel6/900/1100','https://picsum.photos/seed/chantyfinal7/900/1100'];
const caps=['A journey begins','Somewhere on the way','The people make it special','Classroom chaos','The laughs between lessons','Another road, another memory','And one more chapter'];
function snd(f=440){try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.value=.08;o.start();o.stop(audio.currentTime+.12)}catch(e){}}
function startMusic(){music.play().then(()=>mb.textContent='🔊').catch(()=>{})}mb.onclick=()=>music.paused?startMusic():(music.pause(),mb.textContent='🔇');
function next(){step++;render()}function render(){bar.style.width=(step/9*100)+'%';({0:mystery,1:doors,2:orb,3:gift,4:memories,5:balloons,6:quiz,7:countdown,8:message,9:finale}[step]())}
function mystery(){S.innerHTML='<section class="scene"><div class="k">classified birthday file • C20</div><h1>Hey Chanty…</h1><p class="sub">Today is not going to be a normal birthday wish.</p><button class="btn" id="a">DON’T TAP THIS 👀</button></section>';a.onclick=()=>{snd(720);startMusic();S.innerHTML='<section class="scene"><div class="k">ACCESS GRANTED</div><h2>I KNEW YOU’D TAP IT 😂</h2><p class="sub">Choose a path. One of them hides the next clue.</p><button class="btn" id="b">OPEN SECRET MAP</button></section>';b.onclick=next}}
function doors(){S.innerHTML='<section class="scene"><div class="k">chapter 20 • secret map</div><h2>Where should we start?</h2><p class="sub">Only one door unlocks the trail.</p><div class="grid"><button class="card" data-ok=0>🌴<b>The Trip</b><small>old roads</small></button><button class="card" data-ok=1>✨<b>The Secret</b><small>follow this</small></button><button class="card" data-ok=0>🎓<b>The Classroom</b><small>chaos inside</small></button><button class="card" data-ok=0>🎁<b>The Gift</b><small>not yet</small></button></div></section>';document.querySelectorAll('.card').forEach(x=>x.onclick=()=>x.dataset.ok==='1'?(snd(720),next()):(snd(160),x.animate([{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'none'}],180)))}
function orb(){S.innerHTML='<section class="scene"><div class="k">mini game • 5 catches</div><h2>Catch the spark ✨</h2><p class="sub">Tap it five times.</p><b id="n">0 / 5</b><div class="orbarea"><button class="orb" id="o"></button></div></section>';let n=0;o.onclick=()=>{n++;document.getElementById('n').textContent=n+' / 5';snd(500);o.style.left=Math.random()*80+5+'%';o.style.top=Math.random()*75+5+'%';if(n===5)setTimeout(next,400)};o.click()}
function gift(){S.innerHTML='<section class="scene"><div class="k">something is waiting</div><h2>Open the gift</h2><p class="sub">Three taps. Don’t stop early.</p><div class="gift" id="g"><div class="box"></div><div class="lid"></div><div class="ribbon"></div><div class="bow">🎀</div></div><b id="t">0 / 3</b></section>';let n=0;g.onclick=()=>{n++;t.textContent=n+' / 3';snd(n===3?260:440);if(n===3){g.classList.add('open');setTimeout(next,800)}}}
function memories(){S.innerHTML=`<section class="scene"><div class="k">memory trail • ${mem+1}/7</div><h2>${caps[mem]}</h2><div class="mem"><img src="${photos[mem]}"><div class="meminfo"><b>Chanty • Chapter 20</b><span>${mem+1}/7</span></div></div><div class="hint">← Swipe photo →</div><button class="btn" id="mn">${mem===6?'Continue':'Next memory'}</button></section>`;let sx=0,c=document.querySelector('.mem');c.ontouchstart=e=>sx=e.touches[0].clientX;c.ontouchend=e=>{let d=e.changedTouches[0].clientX-sx;if(Math.abs(d)>45){if(d<0&&mem<6){mem++;render()}else if(d>0&&mem>0){mem--;render()}}};mn.onclick=()=>mem<6?(mem++,render()):next()}
function balloons(){S.innerHTML='<section class="scene"><div class="k">birthday challenge</div><h2>Pop 6 balloons 🎈</h2><p class="sub">Find them all.</p><div class="balloons" id="ba"></div><b id="pc">0 / 6</b></section>';let n=0,colors=['#ff4fa3','#55e8ff','#ffe36e','#9d6cff','#ff7b54','#69f0ae'];colors.forEach((c,i)=>{let b=document.createElement('button');b.className='balloon';b.style.cssText=`--c:${c};left:${5+Math.random()*82}%;top:${5+Math.random()*72}%`;b.onclick=()=>{b.remove();snd(560);n++;pc.textContent=n+' / 6';if(n===6)setTimeout(next,500)};ba.appendChild(b)})}
function quiz(){S.innerHTML='<section class="scene"><div class="k">final check</div><h2>How old is Chanty?</h2><p class="sub">Pick the correct answer.</p><div class="quiz">'+[18,19,20,21].map(x=>`<button class="choice" data-x="${x}">${x}</button>`).join('')+'</div></section>';document.querySelectorAll('.choice').forEach(x=>x.onclick=()=>x.dataset.x==='20'?next():(snd(160),x.textContent='NOPE 😂',setTimeout(()=>x.textContent=x.dataset.x,600)))}
function countdown(){S.innerHTML='<section class="scene"><div class="k">get ready</div><div style="font-size:70px;font-weight:800" id="cd">3</div><p class="sub">Something is about to explode.</p></section>';let n=3,t=setInterval(()=>{n--;if(n===0){clearInterval(t);next()}else{cd.textContent=n;snd(440)}},800)}
function message(){let m=`Hey Chanty,<br><br>20 isn't just another number. It's another chapter filled with new places, new memories, new adventures and plenty of moments that will someday become stories we laugh about.<br><br>From travelling together to all those classroom moments, some of the best memories are simply the ones we never planned.<br><br>So here's to more journeys, more laughs, more crazy moments and many more memories waiting to happen.<br><br>Keep smiling. Keep being you. ❤️<br><br><b>Happy 20th Birthday, Chanty! 🎂</b>`;S.innerHTML='<section class="scene"><div class="k">a message from me to you</div><h2>Before the last surprise…</h2><div class="msg" id="m"></div></section>';let i=0;function type(){m.innerHTML=m.slice(0,++i);if(i<m.length)setTimeout(type,15);else setTimeout(next,1200)}type()}
function finale(){S.innerHTML='<section class="scene"><div class="k">wait…</div><h2>There’s one last thing 👀</h2><p class="sub">You thought that was the end?</p><button class="btn" id="r">REVEAL CHAPTER 20</button></section>';r.onclick=()=>{S.innerHTML=`<section class="scene"><div class="k">THE NEXT CHAPTER</div><h1>HAPPY BIRTHDAY<br>CHANTY ❤️</h1><p class="sub">20 years • countless memories • many more to come</p><img class="final" src="${photos[6]}"><p>CHAPTER 20 IS OFFICIALLY OPEN ✨</p></section>`;bar.style.width='100%';snd(80)}}
render();