const C={name:"Someone Special",photo:"assets/photos/birthday-person.jpg",message:`Happy Birthday! 🎂

Twenty is more than a number. It is the beginning of another beautiful chapter — new places, new memories, big dreams and tiny moments worth remembering.

I hope you always keep that spark that makes you, YOU.

May you laugh loudly, dream fearlessly and find a little magic in ordinary days.

Here's to Chapter 20. ✨
With lots of happiness and warm wishes ❤️`,photos:[
{src:"",text:"A memory that deserves its own little star."},{src:"",text:"One moment. A thousand feelings."},{src:"",text:"Some memories never really leave us."},{src:"",text:"A page worth turning back to."},{src:"",text:"The kind of moment you wish you could pause."},{src:"",text:"More memories are waiting to be made."},{src:"",text:"And this story is only getting started."}],quiz:[
["What do you like to do most in your free time?",["Watching phone 📱","Listening to music 🎧","Watching movies 🎬","Sitting alone 🌙"]],
["What would you enjoy doing more?",["Travelling ✈️","Cooking 🍳","Playing 🎮","Trying something completely new ✨"]],
["Which kind of day sounds most like you?",["A peaceful day alone 🌙","A fun day with friends 🫶","An adventure somewhere new 🌍","A cozy movie/music day 🎶"]]]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let scene=0;
function go(n){let a=$(`#s${scene}`),b=$(`#s${n}`);if(!b)return;a.classList.remove("active");a.classList.add("exit");setTimeout(()=>a.classList.remove("exit"),700);b.classList.add("active");scene=n;if(n===8)countdown();if(n===9)type();if(n===10)fireworks()}
$$("[data-go]").forEach(b=>b.onclick=()=>go(+b.dataset.go));
$$('[data-door]').forEach(b=>b.onclick=()=>{let d=b.dataset.door;$('#doorResult').textContent=`The ${d} chose you. ✦`;setTimeout(()=>go(2),750)});
let oc=0,oe=["A tiny spark woke up. ✨","The light remembers something… 🌙","A secret star appeared. ⭐","The orb is getting brighter…","Something magical is getting closer. 🪄","One more tap… 👀","The wish is awake! 💫"];$('#orb').onclick=()=>{oc++;$('#orbCount').textContent=oc;$('#orbText').textContent=oe[oc-1];burst($('#orb'));if(oc>=7)setTimeout(()=>go(3),650)};
let gc=0;$('#gift').onclick=()=>{if(gc>=2)return;gc++;$('#giftCount').textContent=gc;if(gc===2){$('#gift').classList.add('open');confetti();toast('Here we go! ✨');setTimeout(()=>go(4),1100)}};
let mi=0;function memory(){let p=C.photos[mi],box=$('#memoryPhoto');box.textContent=p.src?'':`YOUR PHOTO ${String(mi+1).padStart(2,'0')}`;box.style.backgroundImage=p.src?`url("${p.src}")`:'';$('#memoryCaption').textContent=p.text;$('#dots').textContent=` ${mi+1} / ${C.photos.length} `}function move(d){mi=(mi+d+C.photos.length)%C.photos.length;memory();if(mi===6)setTimeout(()=>go(5),700)}$('#next').onclick=()=>move(1);$('#prev').onclick=()=>move(-1);memory();
let running=false,score=0,miss=0,time=35,falls=[],sp,tm,raf;const game=$('#starGame'),pl=$('#player');function resetStar(){falls.forEach(x=>x.el.remove());falls=[];score=miss=0;time=35;$('#score').textContent=0;$('#miss').textContent=0;$('#time').textContent=35}function pos(x,y){let r=game.getBoundingClientRect();pl.style.left=Math.max(25,Math.min(r.width-25,x-r.left))+'px';pl.style.top=Math.max(25,Math.min(r.height-25,y-r.top))+'px'}game.onpointermove=e=>running&&pos(e.clientX,e.clientY);game.onpointerdown=e=>running&&pos(e.clientX,e.clientY);function spawn(){if(!running)return;let e=document.createElement('i');e.className='fall';e.style.left=(Math.random()*90+5)+'%';e.style.top='-30px';game.append(e);falls.push({el:e,y:-30,s:2.5+Math.random()*2.5})}function loop(){if(!running)return;let pr=pl.getBoundingClientRect();for(let i=falls.length-1;i>=0;i--){let f=falls[i];f.y+=f.s;f.el.style.top=f.y+'px';let r=f.el.getBoundingClientRect(),dx=r.left+r.width/2-(pr.left+pr.width/2),dy=r.top+r.height/2-(pr.top+pr.height/2);if(Math.hypot(dx,dy)<40){f.el.remove();falls.splice(i,1);score++;$('#score').textContent=score;burst(f.el);if(score>=30)endStar(true)}else if(f.y>game.clientHeight+35){f.el.remove();falls.splice(i,1);miss++;$('#miss').textContent=miss;if(miss>3){endStar(false);return}}}raf=requestAnimationFrame(loop)}function startStar(){if(running)return;resetStar();running=true;$('#gameMsg').style.display='none';sp=setInterval(spawn,500);tm=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0)endStar(false)},1000);raf=requestAnimationFrame(loop)}function endStar(win){if(!running)return;running=false;clearInterval(sp);clearInterval(tm);cancelAnimationFrame(raf);falls.forEach(x=>x.el.remove());falls=[];$('#gameMsg').style.display='grid';if(win){$('#gameMsg').textContent='30 stars caught! ✨';$('#startStar').textContent='Continue →';confetti();setTimeout(()=>go(6),900)}else{$('#gameMsg').textContent=miss>3?'Fourth miss! The challenge starts again.':'Time is up! Try again.';$('#startStar').textContent='Start again'}}$('#startStar').onclick=()=>score>=30?go(6):startStar();
/* NEW GAME: three-level memory code */
let code=[],input=[],level=0,watch=false;const sym=$$('.symbols button');function light(x){let b=sym.find(b=>b.dataset.x===x);if(!b)return;b.classList.add('lit');setTimeout(()=>b.classList.remove('lit'),350)}function sequence(){watch=true;$('#codeStatus').textContent='Watch carefully…';code.forEach((x,i)=>setTimeout(()=>light(x),450+i*550));setTimeout(()=>{watch=false;input=[];$('#codeStatus').textContent='Now repeat it!'},450+code.length*550)}function newRound(){level++;code=Array.from({length:level+1},()=>['🌙','⭐','❤️','✨'][Math.floor(Math.random()*4)]);input=[];$('#level').textContent=`Level ${level} / 3`;sequence()}$('#startCode').onclick=()=>{if(level>=3)level=0;newRound()};sym.forEach(b=>b.onclick=()=>{if(watch||!level)return;let x=b.dataset.x;input.push(x);light(x);if(input[input.length-1]!==code[input.length-1]){level=0;input=[];$('#level').textContent='Level 0 / 3';$('#codeStatus').textContent='Wrong code! Try again. 🔐';return}if(input.length===code.length){if(level===3){$('#codeStatus').textContent='Secret unlocked! 🎉';confetti();setTimeout(()=>go(7),850)}else{$('#codeStatus').textContent='Correct! Next level…';setTimeout(newRound,600)}}});
let qi=0;function quiz(){let q=C.quiz[qi];$('#bar').style.width=(qi/C.quiz.length*100)+'%';$('#question').innerHTML=`<h3>${q[0]}</h3>`+q[1].map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>{b.classList.add('selected');toast('Nice choice!');if(qi<C.quiz.length-1){qi++;setTimeout(quiz,500)}else setTimeout(()=>go(8),700)})}quiz();
let counted=false;function countdown(){if(counted)return;counted=true;let n=3;$('#count').textContent=n;let t=setInterval(()=>{n--;if(n<=0){clearInterval(t);$('#count').textContent='✨';setTimeout(()=>go(9),700)}else $('#count').textContent=n},1000)}let typed=false;function type(){if(typed)return;typed=true;let i=0;function run(){if(i<C.message.length){$('#message').textContent+=C.message[i++];setTimeout(run,C.message[i-1]==='\n'?220:27)}else $('#toFinal').hidden=false}run()}$('#toFinal').onclick=()=>go(10);
$('#name').textContent=C.name;let img=$('#personPhoto');img.src=C.photo;img.onload=()=>{img.style.display='block';$('#photoFallback').style.display='none'};
const cv=$('#fx'),ctx=cv.getContext('2d');let rockets=[],parts=[],fxOn=false;function resize(){let d=Math.min(devicePixelRatio||1,2);cv.width=innerWidth*d;cv.height=innerHeight*d;cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener('resize',resize);function launch(x=innerWidth/2,y=innerHeight*.42){rockets.push({x:innerWidth/2,y:innerHeight+10,tx:x,ty:y,s:8,h:Math.random()*360})}function boom(x,y,h){for(let i=0;i<100;i++){let a=Math.random()*6.28,s=1.5+Math.random()*6;parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:1,d:.009+Math.random()*.012,h})}}function fx(){if(!fxOn)return;ctx.fillStyle='rgba(9,0,20,.18)';ctx.fillRect(0,0,innerWidth,innerHeight);for(let i=rockets.length-1;i>=0;i--){let r=rockets[i],dx=r.tx-r.x,dy=r.ty-r.y,d=Math.hypot(dx,dy);r.x+=dx/d*r.s;r.y+=dy/d*r.s;ctx.fillStyle=`hsl(${r.h},100%,75%)`;ctx.beginPath();ctx.arc(r.x,r.y,2,0,6.28);ctx.fill();if(d<12){boom(r.x,r.y,r.h);rockets.splice(i,1)}}for(let i=parts.length-1;i>=0;i--){let p=parts[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.035;p.l-=p.d;ctx.fillStyle=`hsla(${p.h},100%,72%,${p.l})`;ctx.beginPath();ctx.arc(p.x,p.y,1.7,0,6.28);ctx.fill();if(p.l<=0)parts.splice(i,1)}requestAnimationFrame(fx)}function fireworks(){if(fxOn)return;fxOn=true;resize();launch(innerWidth/2,innerHeight*.42);setTimeout(()=>launch(innerWidth*.27,innerHeight*.3),600);setTimeout(()=>launch(innerWidth*.73,innerHeight*.3),1050);setTimeout(()=>launch(innerWidth/2,innerHeight*.24),1500);setInterval(()=>scene===10&&launch(innerWidth/2+(Math.random()-.5)*innerWidth*.6,innerHeight*(.2+Math.random()*.35)),1200);fx();confetti()}
$('#like').onclick=()=>{$('#reactionText').textContent='Thank you! ❤️ I’m so happy you liked it.';$('#reaction').style.display='none'};$('#dislike').onclick=()=>{$('#reactionText').textContent='Thanks for being honest! 😄 Let’s try it again.';$('#reaction').style.display='none';setTimeout(replay,1300)};$('#replay').onclick=replay;function replay(){scene=10;$$('.scene').forEach(s=>s.classList.remove('active','exit'));$('#s1').classList.add('active');scene=1;oc=0;$('#orbCount').textContent=0;$('#orbText').textContent='The orb is waiting…';gc=0;$('#giftCount').textContent=0;$('#gift').classList.remove('open');mi=0;memory();resetStar();level=0;input=[];$('#level').textContent='Level 0 / 3';$('#codeStatus').textContent='Ready?';qi=0;quiz();counted=false;typed=false;$('#message').textContent='';$('#toFinal').hidden=true;$('#reaction').style.display='block';$('#reactionText').textContent=''}function burst(el){let r=el.getBoundingClientRect();for(let i=0;i<8;i++){let p=document.createElement('span');p.textContent='✦';p.style.cssText=`position:fixed;z-index:9;left:${r.left+r.width/2}px;top:${r.top+r.height/2}px;color:#ffd86b;pointer-events:none`;document.body.append(p);let a=Math.random()*6.28,d=40+Math.random()*70;p.animate([{transform:'translate(-50%,-50%) scale(.2)',opacity:1},{transform:`translate(${Math.cos(a)*d}px,${Math.sin(a)*d}px) scale(1.4)`,opacity:0}],{duration:550});setTimeout(()=>p.remove(),600)}}function confetti(){for(let i=0;i<35;i++){let p=document.createElement('span');p.textContent=['✦','✧','•','♥'][Math.floor(Math.random()*4)];p.style.cssText=`position:fixed;z-index:9;left:50%;top:50%;font-size:${10+Math.random()*15}px;color:hsl(${Math.random()*360},100%,75%);pointer-events:none`;document.body.append(p);let x=(Math.random()-.5)*innerWidth*.9,y=(Math.random()-.5)*innerHeight*.9;p.animate([{transform:'translate(0,0)',opacity:1},{transform:`translate(${x}px,${y}px) rotate(600deg)`,opacity:0}],{duration:900+Math.random()*900});setTimeout(()=>p.remove(),2000)}}function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1200)}
