const stage=document.getElementById('stage'),bar=document.getElementById('bar'),music=document.getElementById('music'),musicBtn=document.getElementById('musicBtn'),fx=document.getElementById('fx');
let step=0,mem=0,audio,popped=0;
const photos=['https://picsum.photos/seed/chantytravel1/900/1100','https://picsum.photos/seed/chantytravel2/900/1100','https://picsum.photos/seed/chantyfriends3/900/1100','https://picsum.photos/seed/chantyclass4/900/1100','https://picsum.photos/seed/chantyclass5/900/1100','https://picsum.photos/seed/chantytravel6/900/1100','https://picsum.photos/seed/chantyfinal7/900/1100'];
const caps=['A journey begins','Somewhere on the way','The people make it special','Classroom chaos','The laughs between lessons','Another road, another memory','And one more chapter'];
function snd(f=440){try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;g.gain.value=.07;o.start();o.stop(audio.currentTime+.12)}catch(e){}}
function musicStart(){music.play().then(()=>musicBtn.textContent='🔊').catch(()=>{})}musicBtn.onclick=()=>music.paused?musicStart():(music.pause(),musicBtn.textContent='🔇');
function next(){step++;render()}function render(){bar.style.width=(step/9*100)+'%';({0:intro,1:choose,2:stars,3:gift,4:memories,5:balloons,6:quiz,7:countdown,8:message,9:finale}[step]())}
function intro(){stage.innerHTML='<section class="scene"><div class="k">V3 • THE UNEXPECTED EDITION</div><h1>Chanty,<br>don’t look away.</h1><p class="sub">There is a birthday surprise hidden behind a few ridiculous challenges.</p><button class="btn" id="go">I’M CURIOUS 👀</button><div class="small">Warning: curiosity is required.</div></section>';go.onclick=()=>{snd(700);musicStart();next()}}
function choose(){stage.innerHTML='<section class="scene"><div class="k">secret route</div><h2>Pick a memory portal</h2><p class="sub">One route reveals the first clue. The others are decoys.</p><div class="route"><button data-ok=0>🌴<span>TRAVEL</span><small>roads & stories</small></button><button data-ok=0>🎓<span>CLASS</span><small>chaos & laughs</small></button><button data-ok=1>🌟<span>20TH CHAPTER</span><small>the hidden route</small></button><button data-ok=0>🎁<span>GIFT</span><small>too early!</small></button></div></section>';document.querySelectorAll('.route button').forEach(b=>b.onclick=()=>{if(b.dataset.ok==='1'){snd(800);next()}else{snd(150);b.animate([{transform:'rotate(-2deg)'},{transform:'rotate(2deg)'},{transform:'none'}],200)}})}
function stars(){stage.innerHTML='<section class="scene"><div class="k">challenge 01</div><h2>Collect 5 stars ✨</h2><p class="sub">Tap the moving stars before they disappear.</p><b id="sc">0 / 5</b><div class="starfield" id="sf"></div></section>';let n=0,sf=document.getElementById('sf');function add(){let s=document.createElement('button');s.className='star';s.style.setProperty('--c',Math.random()>0.5?'#55e8ff':'#ff4fa3');s.style.left=Math.random()*88+'%';s.style.top=Math.random()*78+'%';sf.appendChild(s);s.onclick=()=>{s.remove();n++;sc.textContent=n+' / 5';snd(600);if(n<5)setTimeout(add,150);else setTimeout(next,500)}}add()}
function gift(){stage.innerHTML='<section class="scene"><div class="k">challenge 02</div><h2>Unlock the birthday box</h2><p class="sub">Tap it three times. The third tap releases the surprise.</p><div class="gift" id="gift"><div class="gbox"></div><div class="glid"></div><div class="gribbon"></div><div class="gbow">🎀</div></div><b id="gt">0 / 3</b></section>';let n=0;gift.onclick=()=>{n++;gt.textContent=n+' / 3';snd(n===3?260:450);if(n===3){gift.classList.add('open');burst(50);setTimeout(next,850)}}}
function memories(){stage.innerHTML=`<section class="scene"><div class="k">THE MEMORY ROAD • ${mem+1}/7</div><h2>${caps[mem]}</h2><div class="photo"><img src="${photos[mem]}"><div class="cap"><b>Chanty • Chapter 20</b><span>${mem+1}/7</span></div></div><div class="swipe">Swipe left/right to travel through the memories</div><button class="btn" id="mn">${mem===6?'Continue the journey':'Next memory'}</button></section>`;let sx=0,c=document.querySelector('.photo');c.ontouchstart=e=>sx=e.touches[0].clientX;c.ontouchend=e=>{let d=e.changedTouches[0].clientX-sx;if(Math.abs(d)>45){if(d<0&&mem<6){mem++;render()}else if(d>0&&mem>0){mem--;render()}}};mn.onclick=()=>mem<6?(mem++,render()):next()}
function balloons(){stage.innerHTML='<section class="scene"><div class="k">challenge 03</div><h2>Clear the sky 🎈</h2><p class="sub">Pop 6 balloons before the celebration can begin.</p><div class="balloonzone" id="bz"></div><b id="pc">0 / 6</b></section>';let n=0,cs=['#ff4fa3','#55e8ff','#ffe36e','#8d67ff','#ff7654','#63e6a5'];cs.forEach(c=>{let b=document.createElement('button');b.className='balloon';b.style.setProperty('--clr',c);b.style.left=Math.random()*84+4+'%';b.style.top=Math.random()*72+5+'%';b.onclick=()=>{b.remove();snd(560);pc.textContent=++n+' / 6';if(n===6){burst(80);setTimeout(next,550)}};bz.appendChild(b)})}
function quiz(){stage.innerHTML='<section class="scene"><div class="k">challenge 04 • final lock</div><h2>How old is Chanty?</h2><p class="sub">The final lock only accepts one number.</p><div class="quiz">'+[18,19,20,21].map(x=>`<button class="choice" data-a="${x}">${x}</button>`).join('')+'</div></section>';document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>b.dataset.a==='20'?next():(snd(150),b.textContent='LOCKED 😂',setTimeout(()=>b.textContent=b.dataset.a,650)))}
function countdown(){stage.innerHTML='<section class="scene"><div class="k">all locks opened</div><div class="count" id="num">3</div><h2>Ready?</h2><p class="sub">This is the part where everything changes.</p></section>';let n=3,t=setInterval(()=>{n--;if(n===0){clearInterval(t);burst(170);next()}else{num.textContent=n;snd(430)}},800)}
function message(){let m=`Hey Chanty,<br><br>20 isn't just another number. It's another chapter filled with new places, new memories, new adventures and plenty of moments that will someday become stories we laugh about.<br><br>From travelling together to all those classroom moments, some of the best memories are simply the ones we never planned.<br><br>So here's to more journeys, more laughs, more crazy moments and many more memories waiting to happen.<br><br>Keep smiling. Keep being you. ❤️<br><br><b>Happy 20th Birthday, Chanty! 🎂</b>`;stage.innerHTML='<section class="scene"><div class="k">one serious moment</div><h2>Okay… no more games.</h2><div class="message" id="typed"></div></section>';let i=0;function type(){typed.innerHTML=m.slice(0,++i);if(i<m.length)setTimeout(type,14);else setTimeout(next,1400)}type()}
function finale(){stage.innerHTML='<section class="scene"><div class="k">OR IS IT?</div><h2>Wait… there’s one final thing 👀</h2><p class="sub">Tap only when you’re ready to open Chapter 20.</p><button class="btn" id="reveal">OPEN THE FINAL SURPRISE</button></section>';reveal.onclick=()=>{burst(280);stage.innerHTML=`<section class="scene"><div class="k">THE NEXT CHAPTER</div><h1>HAPPY<br>BIRTHDAY<br>CHANTY ❤️</h1><p class="sub">20 years • countless memories • unlimited adventures ahead</p><img class="finalimg" src="${photos[6]}"><p class="small">CHAPTER 20 IS OFFICIALLY OPEN ✨</p></section>`;bar.style.width='100%';snd(80)}}
function burst(count){for(let i=0;i<count;i++){let p=document.createElement('i');p.style.cssText=`position:fixed;left:50%;top:52%;width:${3+Math.random()*7}px;height:${3+Math.random()*7}px;border-radius:50%;background:${['#ff4fa3','#55e8ff','#ffe36e','#8d67ff','#fff'][Math.floor(Math.random()*5)]};z-index:50`;document.body.appendChild(p);let a=Math.random()*6.28,r=100+Math.random()*Math.min(innerWidth,innerHeight)*.8,x=Math.cos(a)*r,y=Math.sin(a)*r;p.animate([{transform:'translate(-50%,-50%)',opacity:1},{transform:`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`,opacity:0}],{duration:800+Math.random()*900}).onfinish=()=>p.remove()}}
render();